spring:
  application:
    name: escalas

  datasource:
    url: jdbc:postgresql://localhost:5432/escalas
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:Admin123!}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update